version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /.*
  script: blog.app
  
libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
